#!/usr/bin/env python3
"""Install compatibility maintenance entry points into a Hermes profile.

Profile plugin source and projection ownership moved to the external ``agents``
repository. This compatibility path now supports only ``--maintenance-only``
for existing scheduled procedures. Plugin installation through this Hermes
checkout is intentionally refused so the retired source tree cannot return.
"""

from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path
# Cron --script jobs resolve scripts under $HERMES_HOME/scripts. These are the candidate's
# scheduled procedures (see maintenance/runtime-ownership.md); copied, never symlinked, so a
# checkout move or worktree removal cannot break a scheduled job.
CRON_SCRIPTS = (
    ("scripts", "sync_fork_candidate.py"),
    ("scripts", "check_fork_patches.py"),
    ("scripts", "curate_skill_observations.py"),
    ("scripts", "cron_migration_diff.py"),
    ("scripts", "schema_rehearsal.py"),
    ("candidate-profile", "snapshot_profile_state.sh"),
)


def install_maintenance(home: Path) -> list[str]:
    """Keep scheduler entry points stable while the native updater owns their code."""
    home = home.expanduser().resolve()
    scripts = home / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    names = ["sync_fork_candidate.py", "check_fork_patches.py"]
    for name in names:
        content = (
            "#!/usr/bin/env python3\n"
            "# Generated by scripts/install_candidate_extensions.py --maintenance-only.\n"
            "import os, runpy, sys\nfrom pathlib import Path\n"
            "home = Path(os.environ.get('HERMES_HOME') or Path(__file__).resolve().parents[1])\n"
            "root = home / 'hermes-agent'\n"
            "sys.path.insert(0, str(root))\n"
            f"runpy.run_path(str(root / 'scripts' / {name!r}), run_name='__main__')\n"
        )
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=scripts, delete=False) as tmp:
            tmp.write(content)
        Path(tmp.name).chmod(0o700)
        os.replace(tmp.name, scripts / name)
    wrapper = "sync_fork_candidate_job.sh"
    with tempfile.NamedTemporaryFile(dir=scripts, delete=False) as tmp:
        tmp.write((_repo_root() / "scripts" / wrapper).read_bytes())
    Path(tmp.name).chmod(0o700)
    os.replace(tmp.name, scripts / wrapper)
    return names + [wrapper]


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def install(home: Path, source: Path | None = None) -> list[str]:
    """Refuse the retired in-checkout plugin installation route."""
    del home, source
    raise SystemExit(
        "profile plugin installation moved to the external agents repository; "
        "use its target build/projection workflow"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--home", type=Path, required=True, help="Target HERMES_HOME profile")
    parser.add_argument("--source", type=Path, help="Deprecated and ignored for plugin installation")
    parser.add_argument("--maintenance-only", action="store_true", help="refresh only sync/verifier entry points, without touching plugins or config")
    args = parser.parse_args()
    names = install_maintenance(args.home) if args.maintenance_only else install(args.home, args.source)
    print(f"installed {', '.join(names)} into {args.home.expanduser().resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
